# -*- coding: utf-8 -*-
"""Content data for the 12 remaining city pages. Build order follows README priority."""

CITIES = [
    {
        "slug": "frisco", "name": "Frisco", "county": "Collin County",
        "lat": 33.1507, "lng": -96.8236,
        "title": "Epoxy Flooring Frisco, TX | Garage &amp; Metallic Coatings | Epoxy Magicians",
        "meta_desc": "Epoxy garage, metallic &amp; polyaspartic floor coatings in Frisco, TX. Local crews, free estimates, same-week install. Built for Frisco's new-build slabs. Call [[PHONE]].",
        "hero_p": "Garage, metallic and polyaspartic floor coatings for Frisco's fast-growing neighborhoods &mdash; installed by a local crew that knows new-construction slabs. Free estimates, same-week install.",
        "hero_img_alt": "Metallic epoxy garage floor completed at a Frisco, Texas home by Epoxy Magicians",
        "intro": "Epoxy Magicians installs garage floor epoxy, metallic epoxy and polyaspartic coatings throughout Frisco, Texas &mdash; from Starwood and Phillips Creek Ranch to the newer communities near The Star and Frisco Square.",
        "neighborhoods_h2": "Neighborhoods we coat in Frisco",
        "neighborhoods_p": "We regularly install floors across Frisco, including <strong>Starwood, Phillips Creek Ranch, Newman Village, Frisco Square, Panther Creek, and the communities surrounding The Star (Cowboys headquarters)</strong>. Frisco is one of the fastest-growing cities in the country, and most of the slabs we coat here are less than 15 years old &mdash; but new doesn't always mean ready to coat.",
        "soil_h2": "Why even new Frisco slabs need proper prep",
        "soil_p": "Frisco sits on the same expansive clay soil as the rest of Collin County, and builder-grade concrete is poured fast to keep up with new-home demand &mdash; it's common for a slab that looks brand new to still have surface contamination from curing compounds, or hairline cracks from rapid initial settling. We diamond-grind every Frisco garage regardless of the home's age, because grinding is what removes that curing compound and opens the surface for a real mechanical bond. Skipping this step is the #1 reason we get called to fix a peeling floor that a big-box DIY kit was rolled directly onto.",
        "pricebox": "Epoxy flooring cost in Frisco: flake garage systems run <strong>$5&ndash;$8/sq ft</strong>, metallic <strong>$8&ndash;$12/sq ft</strong>. A typical 2-car Frisco garage is <strong>$1,800&ndash;$4,500 installed</strong>. Many HOAs in Frisco's newer communities have exterior finish guidelines &mdash; we can work within your HOA's requirements for driveway or entry coatings.",
        "popular_h2": "Popular in Frisco garages",
        "popular_items": [
            "<strong>Metallic epoxy</strong> &mdash; a frequent request in Frisco's newer luxury builds and finished-out garages that double as workshop or hobby space.",
            "<strong>Flake / chip floors</strong> &mdash; durable and versatile for growing families with active garages.",
            "<strong>Polyaspartic one-day install</strong> &mdash; ideal for busy households near The Star and Frisco's business corridor who need the garage back fast.",
        ],
        "review_area": "Starwood",
        "faqs": [
            ("Do you install garage epoxy in Frisco?", "Yes &mdash; throughout Frisco, including Starwood, Phillips Creek Ranch, Newman Village and the area around The Star. Estimates are free and most garages finish in one day."),
            ("How much does epoxy flooring cost in Frisco?", "$5&ndash;$8/sq ft for flake and $8&ndash;$12/sq ft for metallic. A 2-car garage typically runs $1,800&ndash;$4,500 installed."),
            ("Do new-construction Frisco homes still need slab grinding?", "Yes. Builder-grade slabs often carry curing compound residue and can have early settling cracks. We diamond-grind every job, new or old, for proper adhesion."),
        ],
    },
    {
        "slug": "mckinney", "name": "McKinney", "county": "Collin County",
        "lat": 33.1972, "lng": -96.6397,
        "title": "Epoxy Flooring McKinney, TX | Garage &amp; Metallic Coatings | Epoxy Magicians",
        "meta_desc": "Epoxy garage, metallic &amp; polyaspartic floor coatings in McKinney, TX. Local crews, free estimates, same-week install. Serving historic and new McKinney alike. Call [[PHONE]].",
        "hero_p": "Garage, metallic and polyaspartic floor coatings for McKinney homes old and new &mdash; from Historic Downtown to Stonebridge Ranch. Free estimates, same-week install.",
        "hero_img_alt": "Flake epoxy garage floor completed at a McKinney, Texas home by Epoxy Magicians",
        "intro": "Epoxy Magicians installs garage floor epoxy, metallic epoxy and polyaspartic coatings throughout McKinney, Texas &mdash; a city where we regularly work on both century-old slabs near the historic square and brand-new construction in Craig Ranch.",
        "neighborhoods_h2": "Neighborhoods we coat in McKinney",
        "neighborhoods_p": "We regularly install floors across McKinney, including <strong>Stonebridge Ranch, Craig Ranch, Historic Downtown McKinney, Eldorado, and Trinity Falls</strong>. McKinney's mix of century-old homes near the square and fast-growing new subdivisions to the west means we see a wider range of slab ages here than almost anywhere else in DFW.",
        "soil_h2": "Old square vs. new subdivision slabs",
        "soil_p": "Homes near Historic Downtown McKinney often have original slabs that are 60-100+ years old, with settling cracks and prior patch repairs from decades of North Texas clay soil movement &mdash; these need more thorough crack chasing and structural polymer repair before coating. Newer Craig Ranch and Trinity Falls slabs are younger but still need full diamond grinding to remove curing compound. Either way, we assess your specific slab at the estimate rather than quoting blind.",
        "pricebox": "Epoxy flooring cost in McKinney: flake garage systems run <strong>$5&ndash;$8/sq ft</strong>, metallic <strong>$8&ndash;$12/sq ft</strong>. A typical 2-car McKinney garage is <strong>$1,800&ndash;$4,800 installed</strong> &mdash; older downtown-area slabs often land at the higher end due to additional crack repair.",
        "popular_h2": "Popular in McKinney garages",
        "popular_items": [
            "<strong>Flake floors</strong> &mdash; the most requested finish for older McKinney homes since the broken color pattern hides settling cracks and patch repairs.",
            "<strong>Metallic epoxy</strong> &mdash; popular in Stonebridge Ranch and Craig Ranch's larger, newer garages.",
            "<strong>Polyaspartic driveway coatings</strong> &mdash; a frequent add-on for McKinney's tree-lined older streets where driveways see heavy shade-to-sun transitions.",
        ],
        "review_area": "Stonebridge Ranch",
        "faqs": [
            ("Do you install garage epoxy in McKinney?", "Yes &mdash; throughout McKinney, including Stonebridge Ranch, Craig Ranch, and the Historic Downtown area. Estimates are free."),
            ("How much does epoxy flooring cost in McKinney?", "$5&ndash;$8/sq ft for flake and $8&ndash;$12/sq ft for metallic. A 2-car garage typically runs $1,800&ndash;$4,800 installed, with older slabs sometimes needing extra crack repair."),
            ("Can you coat over cracks in an old McKinney slab?", "Yes &mdash; we fill and structurally repair cracks with a polymer before grinding and coating, which is especially common on older downtown-area homes."),
        ],
    },
    {
        "slug": "southlake", "name": "Southlake", "county": "Tarrant County",
        "lat": 32.9412, "lng": -97.1342,
        "title": "Epoxy Flooring Southlake, TX | Metallic &amp; Garage Coatings | Epoxy Magicians",
        "meta_desc": "Premium epoxy &amp; metallic garage floor coatings for Southlake, TX custom homes. Free estimates, same-week install. Call [[PHONE]].",
        "hero_p": "High-end garage, metallic and polyaspartic floor coatings for Southlake's custom homes and multi-car garages. Free estimates, same-week install.",
        "hero_img_alt": "High-gloss metallic epoxy floor completed in a Southlake, Texas custom home garage by Epoxy Magicians",
        "intro": "Epoxy Magicians installs garage floor epoxy, metallic epoxy and polyaspartic coatings throughout Southlake, Texas &mdash; a market where 3- and 4-car garages and finished-out shop space are the norm, not the exception.",
        "neighborhoods_h2": "Neighborhoods we coat in Southlake",
        "neighborhoods_p": "We regularly install floors across Southlake, including <strong>Southlake Town Square-area estates, Timarron, Carillon, Monticello, and the larger custom-lot properties throughout the city</strong>. Southlake's larger garages and detached shop buildings mean our jobs here often run bigger in square footage than the DFW average.",
        "soil_h2": "Custom-home slabs &amp; larger garage footprints",
        "soil_p": "Southlake's custom-built homes generally have well-engineered slabs, but the region's clay soil still causes seasonal movement over time, and larger garage and shop floors mean more control joints to manage during grinding and coating. We plan the control-joint layout with you before install &mdash; either honoring the joints in the finished pattern or filling them flush, depending on the look you want for a showcase garage.",
        "pricebox": "Epoxy flooring cost in Southlake: flake systems run <strong>$5&ndash;$8/sq ft</strong>, metallic <strong>$8&ndash;$12/sq ft</strong>. Because Southlake garages and shops often exceed the standard 2-car footprint, most jobs here fall in the <strong>$4,000&ndash;$12,000+</strong> range &mdash; we'll give you an exact number after measuring.",
        "popular_h2": "Popular in Southlake garages",
        "popular_items": [
            "<strong>Metallic epoxy</strong> &mdash; by far our most-requested finish in Southlake, where the garage often functions as a showcase for a car collection.",
            "<strong>Commercial-grade polyaspartic</strong> &mdash; for detached shop buildings that see heavier use than a typical garage.",
            "<strong>Custom color matching</strong> &mdash; many Southlake clients coordinate flake or metallic color with their home's exterior palette.",
        ],
        "review_area": "Timarron",
        "faqs": [
            ("Do you install epoxy in Southlake's larger garages and shops?", "Yes &mdash; we regularly handle 3- and 4-car garages and detached shop buildings throughout Southlake, including Timarron and Carillon."),
            ("How much does epoxy flooring cost in Southlake?", "$5&ndash;$8/sq ft for flake and $8&ndash;$12/sq ft for metallic; because Southlake garages run larger than average, most projects total $4,000&ndash;$12,000+."),
            ("Can you match flake or metallic colors to my home's exterior?", "Yes, we bring physical color samples to the estimate and can special-order blends to coordinate with your home."),
        ],
    },
    {
        "slug": "flower-mound", "name": "Flower Mound", "county": "Denton/Tarrant County",
        "lat": 33.0146, "lng": -97.0969,
        "title": "Epoxy Flooring Flower Mound, TX | Garage &amp; Shop Coatings | Epoxy Magicians",
        "meta_desc": "Epoxy garage &amp; shop floor coatings for Flower Mound, TX homes and equestrian properties. Free estimates, same-week install. Call [[PHONE]].",
        "hero_p": "Garage, shop and polyaspartic floor coatings for Flower Mound's larger lots and equestrian properties. Free estimates, same-week install.",
        "hero_img_alt": "Flake epoxy shop floor completed on a Flower Mound, Texas property by Epoxy Magicians",
        "intro": "Epoxy Magicians installs garage floor epoxy, metallic epoxy and polyaspartic coatings throughout Flower Mound, Texas &mdash; including the larger-lot and equestrian properties that set this town apart from denser DFW suburbs.",
        "neighborhoods_h2": "Neighborhoods we coat in Flower Mound",
        "neighborhoods_p": "We regularly install floors across Flower Mound, including <strong>Bridlewood, Wellington, Lakeside, Highland Village-adjacent areas, and the larger acreage properties</strong> that give Flower Mound its semi-rural character. Many of our jobs here include detached shops and barns in addition to the primary garage.",
        "soil_h2": "Shops, barns &amp; larger slab footprints",
        "soil_p": "Flower Mound's larger lots often mean a detached shop or barn floor in addition to the attached garage, and these outbuilding slabs are sometimes poured to a lower spec than the main house. We evaluate outbuilding slabs separately at the estimate &mdash; older barn or shop floors may need more extensive crack repair or a moisture check before coating, especially on properties near Grapevine Lake where the water table runs higher.",
        "pricebox": "Epoxy flooring cost in Flower Mound: flake systems run <strong>$5&ndash;$8/sq ft</strong>, metallic <strong>$8&ndash;$12/sq ft</strong>. A standard 2-car garage runs <strong>$1,800&ndash;$4,500 installed</strong>; detached shop or barn floors are quoted separately based on square footage and slab condition.",
        "popular_h2": "Popular in Flower Mound",
        "popular_items": [
            "<strong>Flake floors</strong> &mdash; durable and practical for active garages and shop spaces used for equipment storage.",
            "<strong>Polyaspartic shop coatings</strong> &mdash; fast-cure systems for detached shops that can't be out of use for long.",
            "<strong>Metallic epoxy</strong> &mdash; requested for finished-out garages in Bridlewood and Wellington.",
        ],
        "review_area": "Bridlewood",
        "faqs": [
            ("Do you coat detached shops and barns, not just garages?", "Yes &mdash; we regularly coat detached shop and barn floors on Flower Mound's larger properties, quoted separately from the main garage."),
            ("How much does epoxy flooring cost in Flower Mound?", "$5&ndash;$8/sq ft for flake and $8&ndash;$12/sq ft for metallic; a 2-car garage typically runs $1,800&ndash;$4,500 installed."),
            ("Do properties near Grapevine Lake need extra prep?", "Sometimes &mdash; higher water table areas can mean elevated slab moisture, so we check for it before quoting outbuilding floors near the lake."),
        ],
    },
    {
        "slug": "fort-worth", "name": "Fort Worth", "county": "Tarrant County",
        "lat": 32.7555, "lng": -97.3308,
        "title": "Epoxy Flooring Fort Worth, TX | Garage &amp; Shop Coatings | Epoxy Magicians",
        "meta_desc": "Epoxy garage, metallic &amp; polyaspartic floor coatings in Fort Worth, TX. Local crews, free estimates, same-week install. Call [[PHONE]].",
        "hero_p": "Garage, metallic and polyaspartic floor coatings for Fort Worth homes and shops &mdash; from Arlington Heights bungalows to Mira Vista estates. Free estimates, same-week install.",
        "hero_img_alt": "Flake epoxy garage floor completed at a Fort Worth, Texas home by Epoxy Magicians",
        "intro": "Epoxy Magicians installs garage floor epoxy, metallic epoxy and polyaspartic coatings throughout Fort Worth, Texas &mdash; from the historic bungalows near Magnolia Avenue to newer estates in Mira Vista and Aledo-adjacent neighborhoods.",
        "neighborhoods_h2": "Neighborhoods we coat in Fort Worth",
        "neighborhoods_p": "We regularly install floors across Fort Worth, including <strong>Arlington Heights, Mira Vista, Colonial/TCU-area, Near Southside, Chapel Creek, and neighborhoods near the historic Stockyards</strong>. Fort Worth's housing stock spans nearly a century, so our crews are equally comfortable prepping a 1940s bungalow slab and a new-build in a west-side subdivision.",
        "soil_h2": "Fort Worth's clay soil and ranch-style garages",
        "soil_p": "Tarrant County sits on the same expansive clay soil common across North Texas, and Fort Worth's many ranch-style homes often have larger-than-average garages and detached workshops built for trucks and trailers. Older Arlington Heights and Near Southside slabs frequently show settling cracks and prior patch jobs; we structurally repair these with a polymer fill before grinding rather than coating over them, which is the most common shortcut that causes early coating failure.",
        "pricebox": "Epoxy flooring cost in Fort Worth: flake systems run <strong>$5&ndash;$8/sq ft</strong>, metallic <strong>$8&ndash;$12/sq ft</strong>. A typical 2-car garage is <strong>$1,800&ndash;$4,500 installed</strong>; larger ranch-style garages and shops are quoted after measuring.",
        "popular_h2": "Popular in Fort Worth garages",
        "popular_items": [
            "<strong>Flake floors</strong> &mdash; the practical choice for Fort Worth's truck-and-trailer garages and shops.",
            "<strong>Metallic epoxy</strong> &mdash; increasingly requested in Mira Vista and other newer west-side estates.",
            "<strong>Polyaspartic driveway coatings</strong> &mdash; popular for longer driveways common on Fort Worth's larger residential lots.",
        ],
        "review_area": "Arlington Heights",
        "faqs": [
            ("Do you install garage epoxy in Fort Worth?", "Yes &mdash; throughout Fort Worth, including Arlington Heights, Mira Vista, Near Southside and the Stockyards area. Estimates are free."),
            ("How much does epoxy flooring cost in Fort Worth?", "$5&ndash;$8/sq ft for flake and $8&ndash;$12/sq ft for metallic. A 2-car garage typically runs $1,800&ndash;$4,500 installed."),
            ("Can you coat larger ranch-style garages and shops?", "Yes, we regularly handle the larger-than-average garages and detached shops common on Fort Worth's bigger residential lots."),
        ],
    },
    {
        "slug": "arlington", "name": "Arlington", "county": "Tarrant County",
        "lat": 32.7357, "lng": -97.1081,
        "title": "Epoxy Flooring Arlington, TX | Garage &amp; Commercial Coatings | Epoxy Magicians",
        "meta_desc": "Epoxy garage &amp; commercial floor coatings in Arlington, TX. Local crews, free estimates, same-week install. Call [[PHONE]].",
        "hero_p": "Garage, metallic and commercial floor coatings for Arlington homes and businesses &mdash; midway between Dallas and Fort Worth. Free estimates, same-week install.",
        "hero_img_alt": "Flake epoxy garage floor completed at an Arlington, Texas home by Epoxy Magicians",
        "intro": "Epoxy Magicians installs garage floor epoxy, metallic epoxy, and commercial coatings throughout Arlington, Texas &mdash; a city of established family neighborhoods and a growing entertainment-district business corridor around AT&amp;T Stadium and Globe Life Field.",
        "neighborhoods_h2": "Neighborhoods we coat in Arlington",
        "neighborhoods_p": "We regularly install floors across Arlington, including neighborhoods near <strong>Lake Arlington, Viridian, Pantego-adjacent areas, and the established subdivisions built from the 1970s through 1990s</strong> that make up much of the city. We also handle commercial epoxy for businesses in the Entertainment District near the stadiums.",
        "soil_h2": "Established slabs and entertainment-district commercial work",
        "soil_p": "Much of Arlington's housing stock is 30-50 years old, and slabs from that era commonly show settling cracks from decades of clay-soil movement &mdash; we structurally repair these before grinding and coating. On the commercial side, Arlington's Entertainment District businesses often need flooring installed on tight turnarounds around event schedules; we plan commercial jobs around your operating and event calendar.",
        "pricebox": "Epoxy flooring cost in Arlington: flake systems run <strong>$5&ndash;$8/sq ft</strong>, metallic <strong>$8&ndash;$12/sq ft</strong>. A typical 2-car garage is <strong>$1,800&ndash;$4,500 installed</strong>; commercial space near the stadiums is quoted after a walkthrough.",
        "popular_h2": "Popular in Arlington",
        "popular_items": [
            "<strong>Flake floors</strong> &mdash; the most requested finish for Arlington's established family homes.",
            "<strong>Commercial epoxy</strong> &mdash; for restaurants, retail and event-adjacent businesses near the Entertainment District.",
            "<strong>Polyaspartic coatings</strong> &mdash; for homeowners who want a fast, one-day garage turnaround.",
        ],
        "review_area": "Lake Arlington",
        "faqs": [
            ("Do you install garage epoxy in Arlington?", "Yes &mdash; throughout Arlington, including neighborhoods near Lake Arlington and Viridian. Estimates are free."),
            ("How much does epoxy flooring cost in Arlington?", "$5&ndash;$8/sq ft for flake and $8&ndash;$12/sq ft for metallic. A 2-car garage typically runs $1,800&ndash;$4,500 installed."),
            ("Do you do commercial epoxy near the stadiums?", "Yes, we install commercial and industrial epoxy for businesses in Arlington's Entertainment District and can schedule around event-day traffic."),
        ],
    },
    {
        "slug": "dallas", "name": "Dallas", "county": "Dallas County",
        "lat": 32.7767, "lng": -96.7970,
        "title": "Epoxy Flooring Dallas, TX | Garage, Metallic &amp; Commercial Coatings | Epoxy Magicians",
        "meta_desc": "Epoxy garage, metallic &amp; commercial floor coatings in Dallas, TX. Local crews, free estimates, same-week install. Call [[PHONE]].",
        "hero_p": "Garage, metallic and commercial floor coatings for Dallas homes and businesses &mdash; from Lakewood bungalows to Deep Ellum loft conversions. Free estimates, same-week install.",
        "hero_img_alt": "Metallic epoxy garage floor completed at a Dallas, Texas home by Epoxy Magicians",
        "intro": "Epoxy Magicians installs garage floor epoxy, metallic epoxy and commercial coatings throughout Dallas, Texas &mdash; a city with more slab variety than almost anywhere else in the metroplex, from century-old East Dallas bungalows to converted warehouse lofts in Deep Ellum.",
        "neighborhoods_h2": "Neighborhoods we coat in Dallas",
        "neighborhoods_p": "We regularly install floors across Dallas, including <strong>Lakewood, the M Streets, Preston Hollow, Oak Cliff/Bishop Arts, Uptown, and the converted warehouse and loft spaces of Deep Ellum and the Design District</strong>. Because Dallas spans multiple soil zones and building eras, we treat every neighborhood's slabs differently rather than applying a one-size prep approach.",
        "soil_h2": "Old East Dallas slabs vs. new construction",
        "soil_p": "Lakewood and M Streets homes often sit on original 1920s-40s slabs with decades of settling cracks and prior patch work, requiring more thorough structural crack repair before coating. Preston Hollow and newer North Dallas construction have younger slabs but still need full diamond grinding to remove curing compound residue. Deep Ellum and Design District commercial conversions frequently involve older industrial slabs that need moisture testing before a coating system is selected.",
        "pricebox": "Epoxy flooring cost in Dallas: flake systems run <strong>$5&ndash;$8/sq ft</strong>, metallic <strong>$8&ndash;$12/sq ft</strong>. A typical 2-car garage is <strong>$1,800&ndash;$4,800 installed</strong>, with older East Dallas slabs sometimes landing at the higher end due to crack repair. Commercial and loft conversions are quoted after a walkthrough.",
        "popular_h2": "Popular in Dallas",
        "popular_items": [
            "<strong>Flake floors</strong> &mdash; the go-to for East Dallas homes where the pattern hides settling cracks in older slabs.",
            "<strong>Metallic epoxy</strong> &mdash; frequently requested in Preston Hollow and Uptown for showcase garages and finished spaces.",
            "<strong>Commercial epoxy</strong> &mdash; for Deep Ellum and Design District loft, retail and restaurant conversions.",
        ],
        "review_area": "Lakewood",
        "faqs": [
            ("Do you install garage epoxy in Dallas?", "Yes &mdash; throughout Dallas, including Lakewood, Preston Hollow, Oak Cliff and Uptown. Estimates are free."),
            ("How much does epoxy flooring cost in Dallas?", "$5&ndash;$8/sq ft for flake and $8&ndash;$12/sq ft for metallic. A 2-car garage typically runs $1,800&ndash;$4,800 installed."),
            ("Do you handle commercial epoxy for loft or warehouse conversions?", "Yes, we regularly work on Deep Ellum and Design District commercial and loft conversions, including moisture testing for older industrial slabs."),
        ],
    },
    {
        "slug": "denton", "name": "Denton", "county": "Denton County",
        "lat": 33.2148, "lng": -97.1331,
        "title": "Epoxy Flooring Denton, TX | Garage &amp; Shop Coatings | Epoxy Magicians",
        "meta_desc": "Epoxy garage &amp; shop floor coatings in Denton, TX. Local crews, free estimates, same-week install. Call [[PHONE]].",
        "hero_p": "Garage, shop and polyaspartic floor coatings for Denton homes near the Square, UNT and TWU. Free estimates, same-week install.",
        "hero_img_alt": "Flake epoxy garage floor completed at a Denton, Texas home by Epoxy Magicians",
        "intro": "Epoxy Magicians installs garage floor epoxy and polyaspartic coatings throughout Denton, Texas &mdash; a college town with a mix of century-old homes near the historic Square and newer subdivisions toward Lake Lewisville.",
        "neighborhoods_h2": "Neighborhoods we coat in Denton",
        "neighborhoods_p": "We regularly install floors across Denton, including areas near <strong>the historic Denton Square, University of North Texas and Texas Woman's University, Robson Ranch, and the newer subdivisions toward Lake Lewisville</strong>. Denton's older core has some of the oldest residential slabs we work on in the metroplex.",
        "soil_h2": "Older Denton Square-area slabs",
        "soil_p": "Homes near the historic Square are often 60+ years old, with settling cracks typical of Denton County's clay soil and decades of freeze-thaw and drought cycles. We structurally repair these cracks with a polymer fill before grinding, and we're upfront that older slabs may need more prep time quoted into the estimate than a newer Robson Ranch or lakeside build.",
        "pricebox": "Epoxy flooring cost in Denton: flake systems run <strong>$5&ndash;$8/sq ft</strong>, metallic <strong>$8&ndash;$12/sq ft</strong>. A typical 2-car garage is <strong>$1,800&ndash;$4,500 installed</strong>, and we work with Denton homeowners on straightforward, budget-friendly system choices when needed.",
        "popular_h2": "Popular in Denton",
        "popular_items": [
            "<strong>Flake floors</strong> &mdash; a durable, budget-conscious choice popular with Denton homeowners.",
            "<strong>Solid-color epoxy</strong> &mdash; an economical option for garages and shop spaces on a tighter budget.",
            "<strong>Polyaspartic coatings</strong> &mdash; for a fast one-day turnaround near the university areas.",
        ],
        "review_area": "near the Square",
        "faqs": [
            ("Do you install garage epoxy in Denton?", "Yes &mdash; throughout Denton, including areas near the Square, UNT/TWU, and Robson Ranch. Estimates are free."),
            ("How much does epoxy flooring cost in Denton?", "$5&ndash;$8/sq ft for flake and $8&ndash;$12/sq ft for metallic. A 2-car garage typically runs $1,800&ndash;$4,500 installed."),
            ("Do older Denton Square-area homes need extra prep?", "Often yes &mdash; many of these slabs are 60+ years old with settling cracks that need structural repair before coating, which we quote up front."),
        ],
    },
    {
        "slug": "mansfield", "name": "Mansfield", "county": "Tarrant County",
        "lat": 32.5632, "lng": -97.1417,
        "title": "Epoxy Flooring Mansfield, TX | Garage &amp; Metallic Coatings | Epoxy Magicians",
        "meta_desc": "Epoxy garage &amp; metallic floor coatings in Mansfield, TX. Local crews, free estimates, same-week install. Call [[PHONE]].",
        "hero_p": "Garage, metallic and polyaspartic floor coatings for Mansfield's growing family neighborhoods. Free estimates, same-week install.",
        "hero_img_alt": "Flake epoxy garage floor completed at a Mansfield, Texas home by Epoxy Magicians",
        "intro": "Epoxy Magicians installs garage floor epoxy, metallic epoxy and polyaspartic coatings throughout Mansfield, Texas &mdash; one of the fastest-growing family suburbs south of Arlington.",
        "neighborhoods_h2": "Neighborhoods we coat in Mansfield",
        "neighborhoods_p": "We regularly install floors across Mansfield, including <strong>Walnut Creek, Heritage, The Reserve, and the newer subdivisions built out along the US-287 corridor</strong>. Mansfield's rapid growth over the last decade means most of the slabs we coat here are relatively young, though builder-grade prep still varies.",
        "soil_h2": "Newer builds still need full grinding",
        "soil_p": "Mansfield's newer subdivisions sit on the same North Texas clay soil as the rest of Tarrant County, and even recently poured slabs typically carry curing compound residue that prevents a coating from bonding properly if it isn't ground off first. We diamond-grind every job here regardless of the home's build year &mdash; it's the single biggest factor separating a floor that lasts 15+ years from a peeling DIY kit.",
        "pricebox": "Epoxy flooring cost in Mansfield: flake systems run <strong>$5&ndash;$8/sq ft</strong>, metallic <strong>$8&ndash;$12/sq ft</strong>. A typical 2-car garage is <strong>$1,800&ndash;$4,500 installed</strong>.",
        "popular_h2": "Popular in Mansfield garages",
        "popular_items": [
            "<strong>Flake floors</strong> &mdash; the most-requested finish for Mansfield's active family garages.",
            "<strong>Polyaspartic one-day install</strong> &mdash; popular with families who need the garage back quickly.",
            "<strong>Metallic epoxy</strong> &mdash; a growing request as Mansfield's newer, larger-format homes get built out.",
        ],
        "review_area": "Walnut Creek",
        "faqs": [
            ("Do you install garage epoxy in Mansfield?", "Yes &mdash; throughout Mansfield, including Walnut Creek, Heritage, and The Reserve. Estimates are free."),
            ("How much does epoxy flooring cost in Mansfield?", "$5&ndash;$8/sq ft for flake and $8&ndash;$12/sq ft for metallic. A 2-car garage typically runs $1,800&ndash;$4,500 installed."),
            ("Do new Mansfield homes still need slab grinding before coating?", "Yes &mdash; even new slabs carry curing compound residue that must be ground off for the coating to bond properly."),
        ],
    },
    {
        "slug": "rockwall", "name": "Rockwall", "county": "Rockwall County",
        "lat": 32.9312, "lng": -96.4597,
        "title": "Epoxy Flooring Rockwall, TX | Patio, Pool Deck &amp; Garage Coatings | Epoxy Magicians",
        "meta_desc": "Epoxy garage, patio &amp; pool deck coatings in Rockwall, TX. Local crews, free estimates, same-week install. Call [[PHONE]].",
        "hero_p": "Garage, patio and pool deck coatings for Rockwall's lakefront homes around Lake Ray Hubbard. Free estimates, same-week install.",
        "hero_img_alt": "Textured pool deck coating completed at a Rockwall, Texas lakefront home by Epoxy Magicians",
        "intro": "Epoxy Magicians installs garage floor epoxy, patio and pool deck coatings throughout Rockwall, Texas &mdash; a lakefront community where outdoor living space around Lake Ray Hubbard gets as much attention as the garage.",
        "neighborhoods_h2": "Neighborhoods we coat in Rockwall",
        "neighborhoods_p": "We regularly install floors and outdoor coatings across Rockwall, including <strong>The Shores, Chandlers Landing, the Harbor District, and neighborhoods throughout Rockwall and Heath along Lake Ray Hubbard</strong>. Rockwall's lakefront lifestyle means we do a higher share of patio and pool deck work here than in most other DFW cities.",
        "soil_h2": "Lakefront patios and pool decks",
        "soil_p": "Rockwall's lakefront and near-lake properties see heavy outdoor living use, and bare concrete patios and pool decks here take constant sun reflected off the water in addition to direct exposure. We recommend our UV-stable polyaspartic patio and pool deck systems for nearly every outdoor job in Rockwall &mdash; standard epoxy isn't built for this level of sun exposure and will amber within a season or two.",
        "pricebox": "Epoxy &amp; coating cost in Rockwall: garage flake systems run <strong>$5&ndash;$8/sq ft</strong>, metallic <strong>$8&ndash;$12/sq ft</strong>, and patio/pool deck coatings <strong>$6&ndash;$10/sq ft</strong>. A typical 2-car garage runs <strong>$1,800&ndash;$4,500 installed</strong>; pool decks are quoted after measuring.",
        "popular_h2": "Popular in Rockwall",
        "popular_items": [
            "<strong>Patio &amp; pool deck coating</strong> &mdash; our most-requested service in Rockwall given the lakefront outdoor-living culture.",
            "<strong>Flake garage floors</strong> &mdash; durable and practical for boat and lake-gear storage.",
            "<strong>Polyaspartic driveway coatings</strong> &mdash; popular for the long driveways common on Rockwall's larger lakeside lots.",
        ],
        "review_area": "Chandlers Landing",
        "faqs": [
            ("Do you coat pool decks and patios in Rockwall?", "Yes &mdash; this is one of our most-requested services in Rockwall given how much outdoor living happens around Lake Ray Hubbard. Estimates are free."),
            ("How much does pool deck coating cost in Rockwall?", "Typically $6&ndash;$10 per square foot; exact pricing depends on square footage and texture level, quoted after measuring."),
            ("Why not use standard epoxy on a Rockwall patio?", "Standard epoxy isn't UV-stable and will amber under the heavy sun exposure lakefront patios get; we use polyaspartic systems for outdoor work instead."),
        ],
    },
    {
        "slug": "grand-prairie", "name": "Grand Prairie", "county": "Dallas/Tarrant County",
        "lat": 32.7459, "lng": -96.9978,
        "title": "Epoxy Flooring Grand Prairie, TX | Garage &amp; Commercial Coatings | Epoxy Magicians",
        "meta_desc": "Epoxy garage &amp; commercial/industrial floor coatings in Grand Prairie, TX. Local crews, free estimates, same-week install. Call [[PHONE]].",
        "hero_p": "Garage, commercial and industrial floor coatings for Grand Prairie's mix of residential neighborhoods and the I-30 industrial corridor. Free estimates, same-week install.",
        "hero_img_alt": "Commercial epoxy floor completed at a Grand Prairie, Texas warehouse by Epoxy Magicians",
        "intro": "Epoxy Magicians installs garage floor epoxy and commercial/industrial floor coatings throughout Grand Prairie, Texas &mdash; a city that combines established residential neighborhoods with one of DFW's busiest warehouse and distribution corridors along I-30.",
        "neighborhoods_h2": "Areas we serve in Grand Prairie",
        "neighborhoods_p": "We regularly install floors across Grand Prairie, including residential work in <strong>Mira Lagos and the Joe Pool Lake area</strong>, plus commercial and industrial epoxy for warehouses and distribution facilities along the <strong>I-30 and Lake Ridge Parkway corridor</strong>. This mix means our Grand Prairie crews are equally set up for a Saturday garage install and a Tuesday-night warehouse floor.",
        "soil_h2": "Residential slabs and industrial floor demands",
        "soil_p": "Grand Prairie's residential neighborhoods sit on typical North Texas clay soil and need the same diamond-grinding and crack-repair approach we use metro-wide. Our commercial work along the I-30 corridor is a different animal entirely &mdash; warehouse and distribution floors need high-build, forklift-rated systems and installation scheduled around shift changes and shipping deadlines rather than a standard weekday timeline.",
        "pricebox": "Epoxy flooring cost in Grand Prairie: residential flake systems run <strong>$5&ndash;$8/sq ft</strong>, metallic <strong>$8&ndash;$12/sq ft</strong>, with a 2-car garage typically <strong>$1,800&ndash;$4,500 installed</strong>. Commercial and industrial warehouse floors are quoted after a walkthrough based on square footage and traffic load.",
        "popular_h2": "Popular in Grand Prairie",
        "popular_items": [
            "<strong>Commercial &amp; industrial epoxy</strong> &mdash; our most requested service along the I-30 warehouse corridor.",
            "<strong>Flake garage floors</strong> &mdash; the standard choice in Mira Lagos and residential neighborhoods.",
            "<strong>Polyaspartic coatings</strong> &mdash; used for fast-turnaround commercial jobs that can't afford multi-day downtime.",
        ],
        "review_area": "Mira Lagos",
        "faqs": [
            ("Do you do warehouse and industrial epoxy in Grand Prairie?", "Yes &mdash; we regularly install commercial and industrial floor coatings along the I-30/Lake Ridge Parkway corridor, scheduled around your operating hours."),
            ("How much does garage epoxy cost in Grand Prairie?", "$5&ndash;$8/sq ft for flake and $8&ndash;$12/sq ft for metallic. A 2-car garage typically runs $1,800&ndash;$4,500 installed."),
            ("Can you install a warehouse floor without stopping operations?", "In most cases yes &mdash; we schedule industrial jobs at night, on weekends, or in phased sections to minimize disruption."),
        ],
    },
    {
        "slug": "irving", "name": "Irving", "county": "Dallas County",
        "lat": 32.8140, "lng": -96.9489,
        "title": "Epoxy Flooring Irving, TX | Garage &amp; Commercial Coatings | Epoxy Magicians",
        "meta_desc": "Epoxy garage &amp; commercial floor coatings in Irving, TX including Las Colinas. Local crews, free estimates, same-week install. Call [[PHONE]].",
        "hero_p": "Garage and commercial floor coatings for Irving homes and the Las Colinas business district. Free estimates, same-week install.",
        "hero_img_alt": "Commercial epoxy floor completed at a Las Colinas, Irving Texas office building by Epoxy Magicians",
        "intro": "Epoxy Magicians installs garage floor epoxy and commercial floor coatings throughout Irving, Texas &mdash; including the Las Colinas business district's offices, hospitality spaces and canal-front developments.",
        "neighborhoods_h2": "Areas we serve in Irving",
        "neighborhoods_p": "We regularly install floors across Irving, including residential neighborhoods in <strong>Valley Ranch and Irving Ranch</strong>, and commercial epoxy throughout the <strong>Las Colinas business district, the Urban Center canal area, and properties near DFW Airport</strong>. Irving's proximity to DFW Airport also means we regularly work with hospitality and corporate clients who need floors installed with minimal disruption.",
        "soil_h2": "Corporate commercial work and residential garages",
        "soil_p": "Las Colinas commercial and office-building floors typically involve a walkthrough to assess traffic type, whether it's back-of-house restaurant space, a lobby, or a parking structure, before we spec the system. Residential Irving neighborhoods sit on standard North Texas clay soil and get the same diamond-grinding and crack-repair prep as the rest of the metroplex.",
        "pricebox": "Epoxy flooring cost in Irving: residential flake systems run <strong>$5&ndash;$8/sq ft</strong>, metallic <strong>$8&ndash;$12/sq ft</strong>, with a 2-car garage typically <strong>$1,800&ndash;$4,500 installed</strong>. Commercial Las Colinas projects are quoted after a walkthrough.",
        "popular_h2": "Popular in Irving",
        "popular_items": [
            "<strong>Commercial epoxy</strong> &mdash; for Las Colinas offices, hospitality spaces and retail near the Urban Center.",
            "<strong>Flake garage floors</strong> &mdash; the standard choice in Valley Ranch and Irving Ranch.",
            "<strong>Polyaspartic coatings</strong> &mdash; for commercial clients needing fast turnaround near DFW Airport.",
        ],
        "review_area": "Valley Ranch",
        "faqs": [
            ("Do you do commercial epoxy in Las Colinas?", "Yes &mdash; we regularly install commercial floor coatings for Las Colinas offices, hospitality and retail spaces, scheduled to minimize business disruption."),
            ("How much does garage epoxy cost in Irving?", "$5&ndash;$8/sq ft for flake and $8&ndash;$12/sq ft for metallic. A 2-car garage typically runs $1,800&ndash;$4,500 installed."),
            ("Can you work around a hotel or office's operating hours near DFW Airport?", "Yes, we regularly schedule commercial jobs at night or on weekends for hospitality and corporate clients near the airport."),
        ],
    },
]
print(f"{len(CITIES)} cities loaded")
