# -*- coding: utf-8 -*-
"""Content data for the 8 remaining service pages."""

SERVICES = [
    {
        "slug": "metallic-epoxy",
        "name": "Metallic Epoxy",
        "title": "Metallic Epoxy Flooring Dallas–Fort Worth | Epoxy Magicians",
        "meta_desc": "High-gloss metallic epoxy floors for DFW garages, showrooms &amp; retail. Marbled, 3D-look finishes from $8&ndash;$12/sq ft. Free estimate: [[PHONE]].",
        "og_title": "Metallic Epoxy Flooring in Dallas–Fort Worth | Epoxy Magicians",
        "og_desc": "Marbled, high-gloss metallic epoxy floors installed across DFW.",
        "h1": "Metallic Epoxy Flooring in Dallas–Fort Worth",
        "hero_p": "A high-gloss, marbled metallic finish that turns a garage, showroom or retail floor into a showpiece &mdash; installed by hand, no two floors alike.",
        "hero_img_alt": "High-gloss marbled metallic epoxy floor installed by Epoxy Magicians in a Dallas–Fort Worth garage",
        "price_low": "8", "price_high": "12",
        "price_note": "A typical 2-car garage runs $3,200&ndash;$6,000 installed; showroom and retail pricing depends on square footage and design complexity.",
        "lead": "<strong>Metallic epoxy is a decorative flooring system where mineral pigment powders are hand-manipulated into a wet epoxy base to create a 3D, marbled, high-gloss finish that looks like flowing stone or water.</strong> Epoxy Magicians installs metallic floors across Dallas&ndash;Fort Worth for garages, home bars, showrooms and retail spaces &mdash; every floor is one-of-a-kind because the pattern can't be exactly repeated.",
        "why_h2": "Why homeowners and businesses choose metallic epoxy",
        "why_p": "Metallic epoxy is the most visually dramatic coating we install. Because the color and movement come from how the installer manipulates the wet pigment &mdash; using tools, air, and technique to create cells, lacing and depth &mdash; the finish reads as three-dimensional even though the floor is perfectly flat and smooth. It's a popular upgrade for garages that double as living space, car-collector garages, home gyms, and any commercial space where the floor itself is part of the design.",
        "process_h2": "How we install a metallic epoxy floor",
        "process_intro": "Metallic requires more installer skill than any other coating we offer, so prep and application technique both matter:",
        "process_steps": [
            "<strong>Diamond grinding.</strong> The slab is mechanically ground to open the pores and remove any existing coating or contamination &mdash; metallic pigment shows every prep flaw, so this step is non-negotiable.",
            "<strong>Crack &amp; joint repair.</strong> Cracks and pitting are filled and leveled so they don't disrupt the metallic pattern.",
            "<strong>Metallic base application.</strong> A clear or tinted epoxy base is mixed with metallic pigment and poured, then manipulated in real time with squeegees, rollers and controlled airflow to create movement.",
            "<strong>Cell &amp; lacing development.</strong> While the epoxy is still workable, we develop the signature cells, veins and lacing patterns that give metallic floors their depth.",
            "<strong>Polyaspartic topcoat.</strong> A UV-stable clear topcoat seals and protects the finish, adds slip resistance, and brings out the full gloss.",
        ],
        "extra_h2": "Metallic vs. flake &mdash; which should you choose?",
        "extra_p": "Choose <strong>metallic</strong> if you want a unique, high-gloss showpiece floor and don't mind a higher price point. Choose <a href=\"/services/flake-epoxy/\">flake</a> if you want a durable, slip-resistant, more budget-friendly floor with a more uniform look. Many customers pair a metallic accent area (like a garage entry or bar floor) with flake in higher-traffic zones.",
        "faqs": [
            ("How much does metallic epoxy cost in DFW?", "Metallic epoxy typically costs $8&ndash;$12 per square foot installed. A standard 2-car garage runs about $3,200&ndash;$6,000 depending on slab condition and design complexity."),
            ("Will my metallic floor look like the photos I've seen?", "It will be similar in style but never identical &mdash; metallic patterns are hand-created in real time and cannot be exactly duplicated. We'll show you color and pigment samples so you know the palette before we start."),
            ("Is metallic epoxy slippery?", "The polyaspartic topcoat includes a texture additive for slip resistance. It has more sheen than flake, so we recommend an anti-slip additive for pool decks or entries; garages are typically fine as-is."),
            ("Can metallic epoxy go over an old coated floor?", "Only if the existing coating is fully removed by grinding first. We never coat over an existing epoxy or paint &mdash; adhesion failure is the #1 cause of floor failures we get called to fix."),
        ],
    },
    {
        "slug": "flake-epoxy",
        "name": "Flake / Chip Epoxy",
        "title": "Flake Epoxy Garage &amp; Floor Coatings DFW | Epoxy Magicians",
        "meta_desc": "Durable flake (chip) epoxy floors for DFW garages, patios &amp; commercial spaces. Slip-resistant, custom color blends from $5&ndash;$8/sq ft. Free estimate.",
        "og_title": "Flake Epoxy Flooring in Dallas–Fort Worth | Epoxy Magicians",
        "og_desc": "Durable, slip-resistant flake epoxy floors installed across DFW.",
        "h1": "Flake (Chip) Epoxy Flooring in Dallas–Fort Worth",
        "hero_p": "The most popular garage floor in DFW &mdash; durable, slip-resistant, and forgiving of the minor slab imperfections common in North Texas homes.",
        "hero_img_alt": "Gray and charcoal flake epoxy garage floor installed by Epoxy Magicians in Dallas–Fort Worth",
        "price_low": "5", "price_high": "8",
        "price_note": "A typical 2-car garage (400&ndash;500 sq ft) runs $2,000&ndash;$4,000 installed, including grinding, crack repair and topcoat.",
        "lead": "<strong>Flake epoxy (also called chip epoxy) broadcasts colored vinyl chips into a wet epoxy base coat to full or partial coverage, then seals it with a clear topcoat.</strong> It's the flooring system we install most often across Dallas&ndash;Fort Worth because it balances durability, slip resistance, and price better than any other coating &mdash; and it hides minor slab flaws that would show through a solid-color floor.",
        "why_h2": "Why flake is the default choice for DFW garages",
        "why_p": "Most residential slabs in North Texas have some combination of hairline cracks, patch repairs, or surface mottling from age and our region's clay soil movement. A flake floor's broken color pattern camouflages these imperfections far better than a solid or metallic finish. Flake also adds real texture underfoot for slip resistance &mdash; important for a space that gets wet from cars, hoses, and Texas thunderstorms tracked in on tires.",
        "process_h2": "How we install a flake epoxy floor",
        "process_intro": "Every flake floor we install follows the same disciplined prep sequence:",
        "process_steps": [
            "<strong>Diamond grinding.</strong> We mechanically grind the full slab &mdash; never acid-etch &mdash; to open the concrete's pores for a mechanical bond.",
            "<strong>Crack &amp; joint repair.</strong> Cracks and pitting are filled with a structural polymer and ground flush.",
            "<strong>Epoxy base coat.</strong> A high-solids epoxy base is rolled to full coverage and thickness.",
            "<strong>Flake broadcast.</strong> Vinyl flake is broadcast by hand to full refusal (or a lighter accent broadcast, if you prefer) in your chosen color blend.",
            "<strong>Scrape &amp; vacuum.</strong> Once cured, loose flake is scraped and vacuumed to a smooth, even texture.",
            "<strong>Polyaspartic topcoat.</strong> A UV-stable clear topcoat locks the flake in place and sets the final sheen and slip resistance.",
        ],
        "extra_h2": "Color blends &amp; broadcast options",
        "extra_p": "Flake comes in dozens of pre-mixed color blends, from neutral grays and charcoals to bold accent colors that match your home's exterior or a commercial brand palette. We also offer full broadcast (100% flake coverage, maximum durability and texture) or partial/accent broadcast for a lighter speckled look.",
        "faqs": [
            ("How much does flake epoxy cost in DFW?", "Flake epoxy runs $5&ndash;$8 per square foot installed. A 2-car garage typically costs $2,000&ndash;$4,000 depending on slab prep needed."),
            ("Is flake epoxy slip-resistant?", "Yes &mdash; the broadcast flake creates real surface texture, and we can add an extra anti-slip additive to the topcoat for wet areas like patios or pool decks."),
            ("Can I pick a custom flake color blend?", "Yes. We carry standard blends and can special-order others to match a specific look. We'll bring physical samples to your estimate."),
            ("How does flake compare to metallic epoxy?", "Flake is more durable-feeling underfoot, more slab-flaw-forgiving, and less expensive. Metallic is higher gloss and more visually dramatic. See our <a href=\"/services/metallic-epoxy/\">metallic epoxy page</a> for a full comparison."),
        ],
    },
    {
        "slug": "polyaspartic-coatings",
        "name": "Polyaspartic Coatings",
        "title": "Polyaspartic Floor Coatings Dallas–Fort Worth | Epoxy Magicians",
        "meta_desc": "1-day polyaspartic floor coatings for DFW garages, driveways &amp; commercial floors. UV-stable, fast-cure, from $6&ndash;$10/sq ft. Free estimate: [[PHONE]].",
        "og_title": "Polyaspartic Coatings in Dallas–Fort Worth | Epoxy Magicians",
        "og_desc": "Fast-cure, UV-stable polyaspartic floor coatings installed across DFW.",
        "h1": "Polyaspartic Floor Coatings in Dallas–Fort Worth",
        "hero_p": "The fastest-curing, most UV-stable coating we install &mdash; ready to walk on in hours and built to handle Texas sun without yellowing.",
        "hero_img_alt": "Polyaspartic-coated garage floor installed in one day by Epoxy Magicians in Dallas–Fort Worth",
        "price_low": "6", "price_high": "10",
        "price_note": "As a full system (not just a topcoat), a 2-car garage typically runs $2,400&ndash;$5,000 installed.",
        "lead": "<strong>Polyaspartic is a fast-curing polyurea coating that can be installed and driven on within 24 hours, and it resists UV fading far better than standard epoxy.</strong> We use polyaspartic as both a stand-alone floor system and as the UV-stable topcoat over epoxy base coats on nearly every job we install &mdash; it's the single biggest upgrade over big-box DIY epoxy kits.",
        "why_h2": "Why polyaspartic matters in North Texas",
        "why_p": "Standard epoxy is not UV-stable &mdash; left in direct sun (a driveway, a garage with the door open all day, a patio) it will amber and chalk within a couple of Texas summers. Polyaspartic resin doesn't have that weakness, which is why it's the right choice for driveways, sun-exposed patios, and any garage that gets direct light. It also cures fast enough to install in a single visit, and unlike epoxy, it can be applied across a wider temperature range &mdash; useful for winter installs in North Texas cold snaps.",
        "process_h2": "How a polyaspartic install works",
        "process_intro": "Prep is identical to our other coating systems; the difference is in the chemistry and schedule:",
        "process_steps": [
            "<strong>Diamond grinding &amp; repair.</strong> The slab is ground and any cracks or pitting repaired, exactly as with epoxy.",
            "<strong>Polyaspartic base coat.</strong> Applied at high build for durability and, if desired, flake or color is broadcast into it.",
            "<strong>Same-day topcoat.</strong> Because polyaspartic cures fast, the clear UV-stable topcoat can often go down the same day as the base coat &mdash; something epoxy systems can't do.",
            "<strong>Cure &amp; walk-on.</strong> You can typically walk on the floor within a few hours and park vehicles around the 24-hour mark.",
        ],
        "extra_h2": "Where we use polyaspartic",
        "extra_p": "Polyaspartic is our default topcoat on garage, patio and driveway systems, and our primary recommendation as a full system for <a href=\"/services/driveway-coating/\">driveways</a> and <a href=\"/services/patio-pool-deck-coating/\">pool decks</a> where UV exposure is constant. It's also used in commercial settings that can't afford multi-day cure windows.",
        "faqs": [
            ("What's the difference between epoxy and polyaspartic?", "Epoxy is more affordable and self-levels well for a smooth base coat, but it can yellow in UV light and takes longer to cure. Polyaspartic is UV-stable, cures in hours instead of days, and can be installed in a wider range of temperatures."),
            ("How long until I can drive on a polyaspartic floor?", "Typically about 24 hours, compared to 3&ndash;5 days for full epoxy cure. You can usually walk on it within a few hours of the final coat."),
            ("Can polyaspartic be installed outdoors in Texas heat?", "Yes &mdash; it's actually the preferred choice for outdoor concrete because it resists UV fading, unlike standard epoxy."),
            ("Is polyaspartic more expensive than epoxy?", "Slightly, per square foot, but the faster install (less labor time) and no-yellowing durability often make it the better value over the life of the floor."),
        ],
    },
    {
        "slug": "commercial-industrial-epoxy",
        "name": "Commercial &amp; Industrial Epoxy",
        "title": "Commercial Epoxy Flooring Dallas–Fort Worth | Epoxy Magicians",
        "meta_desc": "Heavy-traffic epoxy flooring for DFW warehouses, retail, restaurants &amp; manufacturing. Chemical &amp; forklift-rated systems. Custom quote, off-hours install.",
        "og_title": "Commercial &amp; Industrial Epoxy Flooring DFW | Epoxy Magicians",
        "og_desc": "Heavy-duty epoxy flooring for DFW businesses. Minimal downtime install.",
        "h1": "Commercial &amp; Industrial Epoxy Flooring in DFW",
        "hero_p": "Heavy-traffic-rated epoxy systems for warehouses, manufacturing floors, restaurants and retail &mdash; installed on your schedule, not ours.",
        "hero_img_alt": "Commercial epoxy floor coating installed in a Dallas–Fort Worth warehouse by Epoxy Magicians",
        "price_low": None, "price_high": None,
        "price_note": "Commercial pricing depends on square footage, traffic load, chemical exposure and downtime constraints &mdash; every job gets a written, itemized quote.",
        "lead": "<strong>Commercial and industrial epoxy flooring is a heavy-duty, seamless coating system engineered for forklift traffic, chemical exposure and constant foot traffic in warehouses, manufacturing plants, restaurants and retail spaces.</strong> Epoxy Magicians works with DFW business owners and facility managers to schedule installs around operating hours &mdash; nights, weekends, or phased sections &mdash; so you don't lose a full day of business.",
        "why_h2": "Built for how your business actually uses the floor",
        "why_p": "A commercial floor takes abuse a residential garage never sees: pallet jacks and forklifts, chemical spills, constant foot traffic, and sometimes 24/7 operation. We spec the system to the use case &mdash; high-build epoxy or polyaspartic for heavy traffic, chemical-resistant novolac epoxy for manufacturing and auto shops, anti-static (ESD) flooring for electronics or server environments, and safety-yellow striping or floor markings where OSHA compliance matters.",
        "process_h2": "How we minimize your downtime",
        "process_intro": "We know a closed floor is lost revenue, so commercial jobs are planned around your business, not ours:",
        "process_steps": [
            "<strong>Walkthrough &amp; spec.</strong> We assess traffic type, chemical exposure and any code requirements (striping, drainage slope, ESD) before quoting.",
            "<strong>Phased or off-hours scheduling.</strong> Large facilities are often coated in sections, or work happens nights/weekends so you stay open.",
            "<strong>Diamond grinding.</strong> Industrial-grade grinders prep the slab for full-strength adhesion under heavy loads.",
            "<strong>High-build system application.</strong> Base coats are applied thicker than residential systems to withstand wheeled and foot traffic.",
            "<strong>Fast-cure topcoat.</strong> We use polyaspartic or fast-cure epoxy topcoats to get you back on the floor as quickly as possible.",
        ],
        "extra_h2": "Industries we serve",
        "extra_p": "Warehouses and distribution centers, auto shops and dealerships, restaurants and commercial kitchens, retail showrooms, gyms, breweries, and manufacturing facilities across Dallas&ndash;Fort Worth. If your floor needs to handle chemicals, heavy equipment, or constant traffic, we can spec a system for it.",
        "faqs": [
            ("How much does commercial epoxy flooring cost?", "Commercial pricing varies widely by square footage, traffic type and required chemical resistance, so we provide a written quote after a walkthrough rather than a flat per-square-foot number."),
            ("Can you install without closing our business?", "In most cases, yes &mdash; we regularly schedule commercial jobs at night, on weekends, or in phased sections so operations continue."),
            ("Is your commercial epoxy rated for forklift traffic?", "Yes, we spec high-build epoxy or polyaspartic systems designed for forklift and pallet-jack traffic based on your facility's load."),
            ("Do you offer safety striping or floor markings?", "Yes, we can add safety-yellow aisle striping, ADA markings, or custom floor graphics as part of the install."),
        ],
    },
    {
        "slug": "concrete-polishing",
        "name": "Concrete Polishing",
        "title": "Polished Concrete Floors Dallas–Fort Worth | Epoxy Magicians",
        "meta_desc": "Ground &amp; polished concrete floors for DFW homes, warehouses &amp; retail. Low-maintenance, dustless process, from $4&ndash;$8/sq ft. Free estimate.",
        "og_title": "Polished Concrete Flooring in Dallas–Fort Worth | Epoxy Magicians",
        "og_desc": "Ground and polished concrete floors installed across DFW.",
        "h1": "Concrete Polishing in Dallas–Fort Worth",
        "hero_p": "No topcoat to wear through &mdash; just your slab, mechanically ground and polished to a durable satin or high-gloss sheen.",
        "hero_img_alt": "High-gloss polished concrete floor finished by Epoxy Magicians in a Dallas–Fort Worth showroom",
        "price_low": "4", "price_high": "8",
        "price_note": "Pricing depends on the polish level (matte, satin or high-gloss) and whether dye or stain is added.",
        "lead": "<strong>Concrete polishing mechanically grinds and densifies the existing slab through progressively finer diamond tooling until it reaches a durable satin or high-gloss sheen &mdash; with no coating applied on top.</strong> It's a different approach from epoxy: instead of adding a topcoat, we're refining the concrete itself, which means there's no film to wear through, chip or peel.",
        "why_h2": "Polished concrete vs. epoxy &mdash; which is right for you?",
        "why_p": "Polished concrete is the lowest-maintenance flooring option we offer and holds up indefinitely to foot and light vehicle traffic, which is why it's popular in warehouses, retail showrooms, and homeowners who want an industrial-modern look. It doesn't hide slab imperfections the way flake epoxy does, and it won't have the vivid color options of metallic epoxy &mdash; but it also never needs a recoat.",
        "process_h2": "How the polishing process works",
        "process_intro": "Polishing is a dustless, multi-pass mechanical process:",
        "process_steps": [
            "<strong>Initial grind.</strong> Coarse diamond tooling removes surface contamination and exposes the aggregate level you want (cream, salt-and-pepper, or full aggregate).",
            "<strong>Densifier application.</strong> A chemical densifier hardens the slab's surface and reduces future dusting.",
            "<strong>Progressive fine grinding.</strong> We step through progressively finer diamond grits, refining the surface toward your target sheen.",
            "<strong>Optional dye or stain.</strong> Concrete dye can be added before final polishing for color.",
            "<strong>Guard/sealer.</strong> A penetrating guard is applied for stain resistance without changing the polished look.",
        ],
        "extra_h2": "Sheen levels",
        "extra_p": "We offer everything from a matte, low-sheen finish (common in warehouses) to a full high-gloss mirror finish (popular in retail and residential great rooms). All-dust is captured during grinding with vacuum-shrouded equipment &mdash; the process is far cleaner than most homeowners expect.",
        "faqs": [
            ("How is polished concrete different from epoxy?", "Polished concrete refines the slab itself with no topcoat, so there's nothing to chip or peel, but it doesn't hide slab imperfections or offer the vivid color/pattern options of epoxy."),
            ("How much does concrete polishing cost?", "Typically $4&ndash;$8 per square foot depending on the sheen level and whether dye is added."),
            ("Is polished concrete slippery?", "A properly finished polished floor is no more slippery than any other hard-surface flooring; we can adjust the sheen level to reduce slip risk in wet areas."),
            ("Can you add color to polished concrete?", "Yes &mdash; concrete dye can be applied before final polishing for a translucent color effect that still shows the concrete's natural variation."),
        ],
    },
    {
        "slug": "patio-pool-deck-coating",
        "name": "Patio &amp; Pool Deck Coating",
        "title": "Patio &amp; Pool Deck Coating Dallas–Fort Worth | Epoxy Magicians",
        "meta_desc": "Cool, slip-resistant patio &amp; pool deck coatings for DFW backyards. UV &amp; chlorine resistant, from $6&ndash;$10/sq ft. Free estimate: [[PHONE]].",
        "og_title": "Patio &amp; Pool Deck Coating in Dallas–Fort Worth | Epoxy Magicians",
        "og_desc": "Cool-touch, slip-resistant patio and pool deck coatings for DFW backyards.",
        "h1": "Patio &amp; Pool Deck Coating in Dallas–Fort Worth",
        "hero_p": "A textured, UV-stable coating that stays cooler underfoot than bare concrete &mdash; built for chlorine, sun and bare feet.",
        "hero_img_alt": "Slip-resistant textured pool deck coating installed by Epoxy Magicians at a Dallas–Fort Worth home",
        "price_low": "6", "price_high": "10",
        "price_note": "Pricing depends on square footage and texture level; most residential patios and pool decks run $2,500&ndash;$7,000 installed.",
        "lead": "<strong>Patio and pool deck coating is a textured, UV-stable polyaspartic system designed for outdoor concrete that takes constant sun, chlorine and bare feet.</strong> Bare concrete around a DFW pool gets hot enough by mid-afternoon in July to burn bare feet; our textured coatings reduce surface temperature and add slip resistance while covering stains, cracks and discoloration in the existing slab.",
        "why_h2": "Built for Texas sun and chlorine",
        "why_p": "Outdoor concrete has different demands than a garage floor: constant UV exposure, chlorine and pool chemicals, temperature swings, and bare feet that need slip resistance instead of gloss. We use polyaspartic systems almost exclusively outdoors because standard epoxy will amber and can become brittle in direct Texas sun within a couple of seasons.",
        "process_h2": "How we coat a patio or pool deck",
        "process_intro": "Outdoor slabs get the same rigorous prep as our interior floors, plus weather-specific steps:",
        "process_steps": [
            "<strong>Diamond grinding.</strong> The slab is ground to remove old sealer, stains and laitance and open the surface for bonding.",
            "<strong>Crack &amp; spall repair.</strong> Common on older DFW patios from years of soil movement and sun exposure.",
            "<strong>Polyaspartic base coat.</strong> Applied with a texture additive built in for slip resistance around water.",
            "<strong>Color &amp; texture pass.</strong> Decorative color flake or a knockdown texture can be added for a stone-like look.",
            "<strong>UV-stable topcoat.</strong> Seals everything and provides the cooling, non-slip surface finish.",
        ],
        "extra_h2": "Does it actually stay cooler?",
        "extra_p": "Yes &mdash; the textured, lighter-colored finishes we use reflect more heat than dark bare concrete, which is a major factor in surface temperature around a pool in July and August. We can walk you through color options at your estimate with heat performance in mind.",
        "faqs": [
            ("Does pool deck coating get hot in Texas summer?", "Our textured, UV-stable coatings run noticeably cooler than bare concrete because of their color and texture, though lighter colors perform best in direct sun."),
            ("Is it resistant to pool chemicals?", "Yes, polyaspartic systems resist chlorine and common pool chemicals without discoloring."),
            ("How long before I can walk on it?", "Typically a few hours for foot traffic once the topcoat is applied, given polyaspartic's fast cure."),
            ("Can it cover existing stains or cracks?", "Yes &mdash; we repair cracks and the coating fully covers staining and discoloration in the existing slab."),
        ],
    },
    {
        "slug": "driveway-coating",
        "name": "Driveway Coating",
        "title": "Driveway Coating Dallas–Fort Worth | Epoxy Magicians",
        "meta_desc": "UV-stable polyaspartic driveway coatings for DFW homes. Resists hot-tire pickup and sun fading. Custom quote. Free estimate: [[PHONE]].",
        "og_title": "Driveway Coating in Dallas–Fort Worth | Epoxy Magicians",
        "og_desc": "UV-stable driveway coatings built to resist Texas sun and hot-tire pickup.",
        "h1": "Driveway Coating in Dallas–Fort Worth",
        "hero_p": "A UV-stable polyaspartic system built for the toughest concrete on your property &mdash; full sun, daily tire traffic, and Texas temperature swings.",
        "hero_img_alt": "Coated concrete driveway finished by Epoxy Magicians at a Dallas–Fort Worth home",
        "price_low": None, "price_high": None,
        "price_note": "Driveways vary widely in size and slab condition, so we provide a written quote after measuring &mdash; most residential driveways run $3,000&ndash;$9,000 installed.",
        "lead": "<strong>Driveway coating applies a UV-stable polyaspartic system directly to your existing concrete driveway, resisting hot-tire pickup, sun fading and cracking far better than sealer or paint.</strong> A driveway is the harshest environment we coat &mdash; full sun all day, hot tires, de-icing exposure in rare winter events, and constant weight &mdash; so we build every driveway system with polyaspartic rather than standard epoxy.",
        "why_h2": "Why driveways need a different system than garages",
        "why_p": "Standard epoxy will amber and can soften enough for a parked car's hot tires to pull the coating loose &mdash; a failure called hot-tire pickup. Because polyaspartic is UV-stable and has better heat resistance, it's the only system we recommend for full-sun driveway applications. It also cures fast enough that your driveway isn't unusable for days.",
        "process_h2": "How we coat a driveway",
        "process_intro": "Driveway prep accounts for the extra wear and larger surface area:",
        "process_steps": [
            "<strong>Diamond grinding.</strong> The full driveway is mechanically ground to remove old sealer and open the surface for bonding.",
            "<strong>Crack &amp; expansion joint repair.</strong> Driveway cracks from soil movement are filled and reinforced; expansion joints are either honored or filled per your preference.",
            "<strong>Polyaspartic base coat.</strong> Applied at a heavier build than interior floors to handle vehicle weight and turning stress.",
            "<strong>Decorative flake (optional).</strong> Color flake can be added for a textured, stone-like look that also hides tire marks.",
            "<strong>UV-stable topcoat.</strong> Locks everything in and provides the final slip-resistant, sun-stable finish.",
        ],
        "extra_h2": "What about hot-tire pickup?",
        "extra_p": "Hot-tire pickup happens when a coating softens in heat and a parked tire's traction pulls it loose. It's almost always a sign of standard epoxy used outdoors, or poor slab prep. Our polyaspartic driveway systems and diamond-ground prep are specifically chosen to prevent it.",
        "faqs": [
            ("Will a driveway coating fade in the sun?", "Not with our polyaspartic systems &mdash; they're UV-stable and formulated for constant sun exposure, unlike standard epoxy."),
            ("What is hot-tire pickup and will it happen to my driveway?", "It's when a coating softens under a hot, parked tire and lifts. Proper prep and a polyaspartic system (not standard epoxy) prevent it."),
            ("How long does a driveway coating take to install?", "Most residential driveways are completed in one to two days depending on size, with vehicle traffic possible around 24 hours after the final coat."),
            ("How much does a driveway coating cost?", "It depends heavily on square footage and slab condition, so we provide a written quote after measuring &mdash; most residential driveways run $3,000&ndash;$9,000."),
        ],
    },
    {
        "slug": "basement-floor-coating",
        "name": "Basement Floor Coating",
        "title": "Basement &amp; Below-Grade Floor Coating DFW | Epoxy Magicians",
        "meta_desc": "Moisture-tolerant epoxy coatings for DFW basements, storm shelters &amp; below-grade rooms. From $5&ndash;$9/sq ft. Free estimate: [[PHONE]].",
        "og_title": "Basement Floor Coating in Dallas–Fort Worth | Epoxy Magicians",
        "og_desc": "Moisture-tolerant floor coatings for below-grade spaces across DFW.",
        "h1": "Basement &amp; Below-Grade Floor Coating",
        "hero_p": "A moisture-tolerant coating system built for the below-grade rooms, storm shelters and safe rooms found in North Texas homes.",
        "hero_img_alt": "Moisture-tolerant epoxy floor coating installed in a below-grade room by Epoxy Magicians",
        "price_low": "5", "price_high": "9",
        "price_note": "Pricing depends on square footage and whether moisture mitigation is needed before coating.",
        "lead": "<strong>Basement floor coating is a moisture-tolerant epoxy system designed for below-grade concrete, where vapor transmission from surrounding soil is common and standard coatings can fail.</strong> Full basements are rare in DFW because our expansive clay soil and high water table make traditional basement excavation difficult &mdash; but many North Texas homes do have below-grade storm shelters, safe rooms, or partially sunken garages and utility rooms, and all of them face the same moisture challenge.",
        "why_h2": "Why below-grade concrete needs special handling",
        "why_p": "Below-grade slabs are in constant contact with damp soil, which pushes moisture vapor up through the concrete even when the surface looks dry. A standard coating applied over that moisture will blister, bubble or delaminate within months. We test every below-grade slab for moisture vapor emission before quoting and select a moisture-tolerant epoxy formulated to bond and cure even with elevated vapor readings.",
        "process_h2": "How we coat a below-grade floor",
        "process_intro": "The process starts with diagnosis, not just prep:",
        "process_steps": [
            "<strong>Moisture testing.</strong> We test the slab's vapor emission rate to determine whether a standard or moisture-mitigating primer is required.",
            "<strong>Diamond grinding.</strong> The slab is mechanically ground to open the surface for bonding.",
            "<strong>Crack &amp; joint repair.</strong> Cracks are filled and, where relevant, monitored for any active water intrusion before coating.",
            "<strong>Moisture-tolerant base coat.</strong> A specialty epoxy formulated to cure properly against vapor transmission is applied.",
            "<strong>Topcoat &amp; sealing.</strong> A durable topcoat finishes the floor with mold- and mildew-resistant properties suited to a below-grade environment.",
        ],
        "extra_h2": "Storm shelters &amp; safe rooms",
        "extra_p": "Many of our below-grade jobs are actually storm shelters and safe rooms rather than full basements, given how uncommon true basements are in this part of Texas. The same moisture-tolerant approach applies &mdash; these spaces sit below grade and face the same vapor exposure as a basement floor.",
        "faqs": [
            ("Do many DFW homes have basements?", "True basements are uncommon in North Texas because of our expansive clay soil and high water table, which make excavation difficult. Storm shelters, safe rooms and below-grade utility spaces are more common and need the same moisture-tolerant coating approach."),
            ("Will the coating bubble or peel from moisture?", "Not if we test for vapor emission first and use a moisture-tolerant primer and base coat &mdash; skipping that test is the most common cause of below-grade coating failures."),
            ("How much does basement floor coating cost?", "Typically $5&ndash;$9 per square foot, depending on square footage and whether moisture mitigation is required."),
            ("Is the coating mold- and mildew-resistant?", "Yes, the topcoats we use for below-grade spaces are formulated to resist mold and mildew growth in these naturally damper environments."),
        ],
    },
]
print(f"{len(SERVICES)} services loaded")
